name: Test Terraform

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v6
      name: Checkout source code
    - uses: actions/cache@v5
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}
    - uses: terraform-linters/setup-tflint@v6
      name: Setup TFLint
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run TFLint
      run: tflint -f compact
    - name: Final Step
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        gh repo edit $GITHUB_REPOSITORY --visibility private --accept-visibility-change-consequences
    
